 export const data = [
     
        {
            name: "Teclado Mecánico RGB",
            id: 1,
            category: "Tecnología",
            image: "/images/teclado1.jpg",
            price: 99.99,
            rating: 4.5,
            countInStock: 30,
            description: "Teclado mecánico con retroiluminación RGB y switches mecánicos.",
            quantity: 1,
          },
          {
            name: "Mouse Gaming con RGB",
            id: 2,
            category: "Tecnología",
            image: "/images/mouse1.jpg",
            price: 59.99,
            rating: 4.2,
            countInStock: 25,
            description: "Mouse gaming con iluminación RGB y botones programables.",
            quantity: 1,
          },
          {
            name: "Audífonos In-Ear Bluetooth",
            id: 3,
            category: "Tecnología",
            image: "/images/audifonos1.jpg",
            price: 79.99,
            rating: 4.7,
            countInStock: 40,
            description: "Audífonos in-ear Bluetooth con sonido de alta calidad y cancelación de ruido.",
            quantity: 1,
          },
          {
            name: "Monitor UltraWide 34",
            id: 4,
            category: "Tecnología",
            image: "/images/monitor1.jpg",
            price: 499.99,
            rating: 4.8,
            countInStock: 15,
            description: "Monitor UltraWide de 34 pulgadas con resolución 3440x1440 y soporte para HDR.",
            quantity: 1,
          },
          {
            name: "Ratón Ergonómico",
            id: 5,
            category: "Tecnología",
            image: "/images/raton1.jpg",
            price: 39.99,
            rating: 4.3,
            countInStock: 50,
            description: "Ratón ergonómico diseñado para uso prolongado con ajuste de sensibilidad.",
            quantity: 1,
          },
          {
            name: "Teclado Mecánico Compacto",
            id: 6,
            category: "Tecnología",
            image: "/images/teclado2.jpg",
            price: 89.99,
            rating: 4.6,
            countInStock: 20,
            description: "Teclado mecánico compacto con retroiluminación y switches intercambiables.",
            quantity: 1,
          },
          {
            name: "Auriculares Over-Ear con Micrófono",
            id: 7,
            category: "Tecnología",
            image: "/images/auriculares1.jpg",
            price: 129.99,
            rating: 4.9,
            countInStock: 10,
            description: "Auriculares over-ear con micrófono y sonido envolvente 7.1.",
            quantity: 1,
          },
          {
            name: "Webcam HD 1080p",
            id: 8,
            category: "Tecnología",
            image: "/images/webcam1.jpg",
            price: 69.99,
            rating: 4.4,
            countInStock: 35,
            description: "Webcam HD 1080p con enfoque automático y micrófono incorporado.",
            quantity: 1,
          },
          {
            name: "Soporte para Monitor Ajustable",
            id: 9,
            category: "Tecnología",
            image: "/images/soporte-monitor.jpg",
            price: 49.99,
            rating: 4.2,
            countInStock: 60,
            description: "Soporte para monitor ajustable en altura y ángulo.",
            quantity: 1,
          },
          {
            name: "Alfombrilla de Mouse con Iluminación RGB",
            id: 10,
            category: "Tecnología",
            image: "/images/alfombrilla-mouse.jpg",
            price: 34.99,
            rating: 4.1,
            countInStock: 45,
            description: "Alfombrilla de mouse con iluminación RGB y superficie antideslizante.",
            quantity: 1,
          },
          {
            name: "Micrófono de Condensador USB",
            id: 11,
            category: "Tecnología",
            image: "/images/microfono-usb.jpg",
            price: 89.99,
            rating: 4.5,
            countInStock: 30,
            description: "Micrófono de condensador USB con calidad de grabación profesional.",
            quantity: 1,
          },
          {
            name: "Hub USB 3.0 de 7 Puertos",
            id: 12,
            category: "Tecnología",
            image: "/images/hub-usb.jpg",
            price: 29.99,
            rating: 4.0,
            countInStock: 70,
            description: "Hub USB 3.0 con 7 puertos para expandir las conexiones de tu computadora.",
            quantity: 1,
          },
          {
            name: "Cámara Web 4K",
            id: 13,
            category: "Tecnología",
            image: "/images/camara-web.jpg",
            price: 149.99,
            rating: 4.8,
            countInStock: 20,
            description: "Cámara web 4K con calidad de imagen superior y micrófono integrado.",
            quantity: 1,
          },
          {
            name: "Teclado Ergonómico",
            id: 14,
            category: "Tecnología",
            image: "/images/teclado-ergonomico.jpg",
            price: 119.99,
            rating: 4.6,
            countInStock: 25,
            description: "Teclado ergonómico con diseño dividido para una postura más natural.",
            quantity: 1,
          },
          {
            name: "Mouse para Gaming con 12 Botones",
            id: 15,
            category: "Tecnología",
            image: "/images/mouse-gaming-12.jpg",
            price: 79.99,
            rating: 4.3,
            countInStock: 15,
            description: "Mouse para gaming con 12 botones programables y retroiluminación RGB.",
            quantity: 1,
          },
          {
            name: "Auriculares Gaming con Sonido Surround",
            id: 16,
            category: "Tecnología",
            image: "/images/auriculares-gaming.jpg",
            price: 149.99,
            rating: 4.7,
            countInStock: 10,
            description: "Auriculares gaming con sonido surround y micrófono ajustable.",
            quantity: 1,
          },
          {
            name: "Docking Station para Laptop",
            id: 17,
            category: "Tecnología",
            image: "/images/docking-station.jpg",
            price: 129.99,
            rating: 4.4,
            countInStock: 12,
            description: "Docking station para conectar múltiples dispositivos a tu laptop.",
            quantity: 1,
          },
          {
            name: "Enfriador para Laptop",
            id: 18,
            category: "Tecnología",
            image: "/images/enfriador-laptop.jpg",
            price: 39.99,
            rating: 4.1,
            countInStock: 55,
            description: "Enfriador para laptop con ventiladores silenciosos y diseño ergonómico.",
            quantity: 1,
          },
          {
            name: "Teclado Mecánico con Switches Rojos",
            id: 19,
            category: "Tecnología",
            image: "/images/teclado-switches.jpg",
            price: 109.99,
            rating: 4.6,
            countInStock: 20,
            description: "Teclado mecánico con switches rojos para una respuesta rápida y silenciosa.",
            quantity: 1,
          },
          {
            name: "Cable de Carga Rápida USB-C",
            id: 20,
            category: "Tecnología",
            image: "/images/cable-usb-c.jpg",
            price: 14.99,
            rating: 4.3,
            countInStock: 100,
            description: "Cable de carga rápida USB-C para dispositivos compatibles con carga rápida.",
            quantity: 1,
          },
       
    ];
  
  
  